version: '3.8'

# This compose file is for the initial setup process
services:
  globus-setup:
    image: ghcr.io/zrzrv5/globus-connect-personal-docker:latest
    container_name: globus-setup
    volumes:
      # Mount config directory for persistent setup
      - ./config:/home/gcp/.globusonline
    stdin_open: true
    tty: true
    command: >
      gcp -setup 
      --name "${ENDPOINT_NAME:-MyEndpoint}" 
      --description "${DESCRIPTION:-Globus Connect Personal Endpoint}" 
      --owner "${OWNER_EMAIL:-user@example.com}"
    environment:
      # Set these via .env file or command line
      - ENDPOINT_NAME=${ENDPOINT_NAME:-MyEndpoint}
      - DESCRIPTION=${DESCRIPTION:-Globus Connect Personal Endpoint}
      - OWNER_EMAIL=${OWNER_EMAIL:-user@example.com}
