version: '3.8'

services:
  globus-gcp:
    image: ghcr.io/zrzrv5/globus-connect-personal-docker:latest
    container_name: globus-gcp
    restart: unless-stopped
    volumes:
      # Globus configuration directory (persistent)
      - ./config:/home/gcp/.globusonline
      # Data directory for transfers (adjust path as needed)
      - ./data:/data
      # Additional mount points (uncomment and adjust as needed)
      # - /volume1/photos:/photos:ro           # Read-only photo access
      # - /volume1/documents:/documents        # Read-write document access
      # - /mnt/backup:/backup                  # Backup directory
    environment:
      # Optional: Set custom data directory inside container
      - GCP_DATA_DIR=/home/gcp/.globusonline
    command: >
      gcp -start -restrict-paths "rw/data"
      # Adjust restrict-paths as needed:
      # "rw/data,r/photos,rw/documents"
    # For debugging, you can override the command:
    # command: /bin/bash
    # stdin_open: true
    # tty: true
